### ISSUE TITLE
Pair values with metadata?

### ISSUE THREAD

**Issue by cscherrer** [TuringLang/AdvancedHMC.jl#101]
For [Soss.jl](https://github.com/cscherrer/Soss.jl) I'm moving toward all MCMC results being in the form of iterators. Currently, `sample` returns a pair `(samples, stats)`, which is a bit awkward to work with.

It seems like this is a general problem: we have a value we're interested in (here a single sample) that has some metadata associated with it. We don't always want to throw away the metadata, but we don't want it to get in the way.

This seems like the exact problem addressed by `MacroTools.jl`'s [`@forward` macro](https://github.com/MikeInnes/MacroTools.jl/blob/master/src/examples/forward.jl).

For example, there could be a (maybe general-purpose) `Meta` struct with 

```julia
struct Meta{T,S}
    value :: T
    meta  :: S
end
```

with methods for common functions `@forward`ed to the `.value` field. A new method for `sample` could then return an iterator of `Meta`s. This could be really convenient - the metadata is there is you need it, but stays out of the way for computations.

What do you think?

**Comment by cpfiffer** [comment]
This is actually a big part of what we did over in Turing recently, but hasn't made it over to AdvancedHMC. The plan is to basically return a struct for each step that contains the values and any additional metadata that is a subtype of `AbstractTransition`. I think Kai and I were talking about doing this a week ago.

**Comment by xukai92** [comment]
Definitely agree that an iterator approach is preferred!

We have something like `Meta` already in AHMC already: https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/trajectory.jl#L14. This was mainly introduced to work with Turing's new interface. 

It's a bit hard to use ATM because the `value` in our case is a `PhasePoint` contains both the sample and the corresponding momentum. Now sure if we want to export an iterator of `PhasePoint` to the user or not? Or we make a new one which is similar to `Meta` to export to the user?

**Comment by xukai92** [comment]
The plan to solve this issue is by wrapping over [AbstractMCMC](https://github.com/TuringLang/AbstractMCMC.jl),
which would provide us an iterator and a transducer.

**Comment by yebai** [comment]
We now support the AbstractMCMC interface. https://github.com/TuringLang/AdvancedHMC.jl/pull/259
