### ISSUE TITLE
Multithreading accelerations

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/AdvancedHMC.jl#135]
As Julia 1.3 is out, I was wondering whether there are any ways to accelerate the sampling process by utilizing the multithreading features?

**Comment by xukai92** [comment]
Are you talking about running multiple chains in parallel or something else related to modifying the HMC algorithm itself?

**Comment by wupeifan** [comment]
If there are some ways to exploit that feature in the algorithm implementation that would be great. Otherwise, I can just run the sampler parallelly with different threads

**Comment by wupeifan** [comment]
I see that you guys are going to present this in Vancouver. Welcome! Which session exactly will it be?

**Comment by xukai92** [comment]
> If there are some ways to exploit that feature in the algorithm implementation that would be great. 

Parallelism in HMC is nontrivial due to the iterative nature of the algorithm. We do have some ideas to accelerate the integrator but we haven't explored it yet.

> Otherwise, I can just run the sampler parallelly with different threads

This will work. We already have this option in Turing.

> I see that you guys are going to present this in Vancouver later this week. Welcome! Which session exactly will it be?

Thanks! Our poster is in the afternoon session of AABI. Happy to meet you there!
