### ISSUE TITLE
example of multiple chains drawns simultaneously

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/AdvancedHMC.jl#143]
I am trying to draw multiple chains. Currently, the example in README spits out results like
```
 Info: Finished 5000 sampling steps for 1 chains in 82.0694485 (s)
│   h = Hamiltonian(metric=DiagEuclideanMetric([1.0, 1.0, 1.0, 1.0, 1.0, 1 ...]))
│   τ = NUTS{MultinomialTS,Generalised}(integrator=Leapfrog(ϵ=0.00517), max_depth=10), Δ_max=1000.0)
│   EBFMI_est = 3626.1271642297047
└   average_acceptance_rate = 0.015550580058411168
```
It would be great to see some examples for more than 1 chain.

**Comment by xukai92** [comment]
You can do parallel sampling (either distributed or multi-thread) via Julia's parallel computing functions (https://docs.julialang.org/en/v1/manual/parallel-computing/). A simple distributed example is as below.

```julia
using Distributed 
addprocs(3)

@everywhere begin
### Define the target distribution and its gradient
using Distributions: logpdf, MvNormal
using DiffResults: GradientResult, value, gradient
using ForwardDiff: gradient!

D = 10
target = MvNormal(zeros(D), ones(D))
ℓπ(θ) = logpdf(target, θ)

function ∂ℓπ∂θ(θ)
    res = GradientResult(θ)
    gradient!(res, ℓπ, θ)
    return (value(res), gradient(res))
end

### Build up a HMC sampler to draw samples
using AdvancedHMC

# Sampling parameter settings
n_samples, n_adapts = 12_000, 2_000

# Draw a random starting points
θ_init = rand(D)

# Define metric space, Hamiltonian, sampling method and adaptor
metric = DiagEuclideanMetric(D)
h = Hamiltonian(metric, ℓπ, ∂ℓπ∂θ)
int = Leapfrog(find_good_eps(h, θ_init))
prop = NUTS{MultinomialTS,GeneralisedNoUTurn}(int)
adaptor = StanHMCAdaptor(
    Preconditioner(metric), 
    NesterovDualAveraging(0.8, int)
)
end

# Draw samples via simulating Hamiltonian dynamics
# - `samples` will store the samples
# - `stats` will store statistics for each sample
pairs = pmap(i -> sample(h, prop, θ_init, n_samples, adaptor, n_adapts; progress=true), 1:4)
```

- `addprocs(3)` indicates the use of 3 additional cores
- Simply wrap some declartions using `@everywhere`
- `pmap(..., 1:4)` indicates running of 4 chains in parallel.

**Comment by wupeifan** [comment]
Thanks for the parallelized example!
So the "1 chain" in `info` is rather some redundant information, as the sampler will always draw 1 chain?

**Comment by xukai92** [comment]
This is related to https://github.com/TuringLang/AdvancedHMC.jl/pull/117 and https://github.com/TuringLang/AdvancedHMC.jl/issues/140. Since https://github.com/TuringLang/AdvancedHMC.jl/pull/117, AHMC supports vectorized sampling for *static* HMC. This means you can take use of SIMD or GPU to do parallel sampling. In this vectorized mode, you can draw multiple chain from a simple `sample` function. This is sort-of alpha functionality and is not documented yet. But if you want to try, see https://github.com/TuringLang/AdvancedHMC.jl/blob/master/test/hmc_mat.jl - basically you just need to initalise the initial parameter as a matrix in which each column is an initial point for a chain, the whole sampling will multi chain. 

However, as mentioned in https://github.com/TuringLang/AdvancedHMC.jl/issues/140, the implementation for NUTS is more difficult due to the nature of dynamic trajecotry, thus not implemented yet.

**Comment by wupeifan** [comment]
I see. Thanks! It's clear.

**Comment by yebai** [comment]
Maybe add aN example on vectorised/threaded HMC to the README.md?

**Comment by wupeifan** [comment]
Yeah, that was what I suggested... And the example that Kai posted here looks legit.

**Comment by Vaibhavdixit02** [comment]
I think we should have an addition to the readme with a multi-threaded example and discuss the vectorised implementation in the docs in more detail?

**Comment by xukai92** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/197.
