### ISSUE TITLE
Tempering with multiplication of momentum leap frog step

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#52]
As requested by @jonasmac16, it would be nice to have this implemented; see Section 5.7 of Neal, 2012.

**Comment by jonasmac16** [comment]
As suggested by Kai on Slack tempering would need to be added to the 'step' function

>  Secondly, you need to add the tempering steps to (https://github.com/TuringLang/AdvancedHMC.jl/blob/637c2be9b424a09d228657b10ee8fa511a0767b8/src/integrator.jl#L37-L65)

Making sure to that we "heat up" and "cool down" symmetrically as suggested by [Neal, 2012](https://arxiv.org/pdf/1206.1901.pdf). As pointed out by Kai due to nature of the leapfrog implementation taking full step for the momentum within the trajectory we need to take extra care.

An `if elseif` scheme for tempering with the trajectory like this should probably work:
```
n_steps =  5

println("Step:0")
println("half*sqrt(α)")
for i in 1:n_steps
  if i*2 == n_steps && i != n_steps
      #θ, r = θ_new, r_new/α
      println("half*sqrt(α) + half/sqrt(α) = full")
      println("Step:",i,".5")
  elseif 2*i < n_steps
      #θ, r = θ_new, r_new*α
      println("full*α")
      println("Step:",i,".5")
  elseif i*2 > n_steps  && i != n_steps
      #θ, r = θ_new, r_new/α
      println("full/α")
      println("Step:",i,".5")
  else
      #θ, r = θ_new, r_new/α_sqrt
      println("full/sqrt(α)")
      println("Step:",i)
  end
end
```

Lastly, @xukai92 raised the issue of how to exactly implement the tempering code within the existing code structure as well as how much effect it will have on `AHMC` sampling:

> So it comes to a design issue, should I implement this conditions inside `step` and check if `lf.α == 1`, or we’d better introduce another `Integrator` type which does this job and implement `lf_momentum` and `lf_position` separate for each type and rely on multiple dispatch to deal with this conditions. Not sure what’s the better way. But for your purpose add this conditions should work.
**However**, I’m not sure how does this actually interact with NUTS (for plain HMC it seems all good), as NUTS only call `steps` with `n_steps=1` and the trajectory building relies on its on doubling tree algorithm.

**Comment by jonasmac16** [comment]
An update from above code(fixing an error), the tempering could be conceptually done like this:
```
n_steps =  5

α = 1.02
α_sqrt = sqrt(α)

println("Step:0")
#θ, r = θ_new, r_new*α_sqrt
println("half*sqrt(α)")
for i in 1:n_steps
  if i*2 == n_steps && i != n_steps
      #θ, r = θ_new, r_new
      println("half*sqrt(α) + half/sqrt(α) = full")
      println("Step:",i,".5")
  elseif 2*i < n_steps
      #θ, r = θ_new, r_new*α
      println("full*α")
      println("Step:",i,".5")
  elseif i*2 > n_steps  && i != n_steps
      #θ, r = θ_new, r_new/α
      println("full/α")
      println("Step:",i,".5")
  else
      #θ, r = θ_new, r_new/α_sqrt
      println("full/sqrt(α)")
      println("Step:",i)
  end
end
```
